version: '3.7'

services:
  listener_app1:
    build: ./packages/listener
    environment:
      NETWORK_URL: https://api.baobab.klaytn.net:8651/
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: indexerdb
      DB_USERNAME: root
      DB_PASSWORD: rootpassword